### PR TITLE
cleanup: remove qt libraries from snap

### PR DESCRIPTION
**Pull request by ppd**
They are provided by the content snaps.

### CODE REVIEW

**Comment by ppd** [comment]
Savings: 66 MB compressed (~10%), quite good. Let's test it further in edge.

```
  latest/edge:      0.21-g842fd477 2022-07-13 (134) 650MB -
installed:          0.21-gedcd16af            (136) 584MB -
```

**Comment by ppd** [comment]
@luzpaz This is also in current edge and edge/toponaming. If you could confirm that everything's working for you, too, I'd cherry-pick this commit for stable.

**Comment by luzpaz** [comment]
I will keep my eyes open. Perhaps we can postpone cherry-picking and wait a few weeks to see if any other edge users report weirdness, thoughts?

**Comment by ppd** [comment]
Yeah, that's the plan. With the new PR publishing system, we have two stages (1. PR, 2. edge) before a change hits stable.

**Pull request merged**
