### PR TITLE
Bump stable to v0.20.1 (bugfix release)

### PR DESCRIPTION
**Pull request by luzpaz**
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.1

@ppd what is the way to dry-run this before pushing live ?

### CODE REVIEW

**Comment by ppd** [comment]
This will get pushed to `candidate` first. If we're satisfied, we can release it to `stable` manually.

**Comment by ppd** [comment]
In principle, we could also cherry-pick the Build PR workflow into stable. Then, you'd be able to build this as a branch, too (safe to publish label etc.).

**Comment by ppd** [comment]
https://github.com/FreeCAD/FreeCAD-snap/runs/7768706157?check_suite_focus=true

**Comment by luzpaz** [comment]
Thanks for confirming ppd :+1: 

CC @donovaly (JFYI, snap stable (v0.20.1) is live :wink:)

**Comment by ppd** [comment]
Is it? I still see rev 161 in stable.

**Comment by luzpaz** [comment]
Correction: technically, it will be live soon.

**Pull request merged**
