### PR TITLE
Update to 0.20.2 release

### PR DESCRIPTION
**Pull request by adrianinsaval**

### CODE REVIEW

**Comment by luzpaz** [comment]
Thought it took more than that to update stable.

**Comment by adrianinsaval** [comment]
you tell me, I just followed what was done for 0.20.1 https://github.com/FreeCAD/FreeCAD-snap/pull/52/files

**Comment by adrianinsaval** [comment]
from the comments I think when you merge this it will be pushed to candidate, then you can test if it works correctly and push it to stable, but this I have no clue how to do

**Comment by adrianinsaval** [comment]
it's in candidate now, could you test it and if it's working move it to stable?

**Comment by adrianinsaval** [comment]
friendly reminder to move 0.20.2 from candidate to stable @luzpaz @ppd

**Comment by luzpaz** [comment]
Added instructions on how to update stable snaps in https://github.com/FreeCAD/FreeCAD-snap/blob/master/docs/index.md#how-to-make-a-new-stable-release (9021367394ba184c3edf513fbe45b15571e4d166)

**Pull request merged**
