### PR TITLE
Testing: TechDaw centerat and Paint functionality

### PR DESCRIPTION
**Pull request by luzpaz**
Build experimental snaps for https://github.com/FreeCAD/FreeCAD/pull/7307  

CC @benj5378

### CODE REVIEW

**Comment by luzpaz** [comment]
Failed to build due to  
> Run sudo snapcraft --destructive-mode
Running with 'sudo' may cause permission errors and is discouraged. Use 'sudo' when cleaning.
Failed to pull source: unable to determine source type of 'https://github.com/benj5378/FreeCAD'.
Check that the URL is correct or consider specifying `source-type` for this part. See `snapcraft help sources` for more information.
Error: Process completed with exit code 2.

**Comment by luzpaz** [comment]
Looks like it was missing `.git` extension. Added in [6936b91](https://github.com/FreeCAD/FreeCAD-snap/pull/47/commits/6936b9106b7a901b717a1b3157d471abb0a93b2e)

**Comment by luzpaz** [comment]
@ppd any idea why no output occurred after build completed?

**Comment by ppd** [comment]
Yeah, sorry. That's an undocumented problem with the Actions API: https://github.com/orgs/community/discussions/25220
I added a workaround. Could you rebase this branch on top of current master?

**Comment by luzpaz** [comment]
Rebased. Thanks!

**Comment by luzpaz** [comment]
Closing

**Pull request closed without merging**
