### PR TITLE
DO NOT MERGE: test new workflows

### PR DESCRIPTION
**Pull request by ppd**

### CODE REVIEW

**Comment by ppd** [comment]
@luzpaz That's a test for a more convenient build process for branches. The idea is as follows:

1. There's a FreeCAD branch somewhere you or the author wishes to publish as a snap
2. You or the author creates a PR on the FreeCAD-snap with the `source-branch` or `source-commit` pointing to their repo/branch
3. You label the PR as "safe to publish" to allow it to be built and published
4. The workflow builds this PR and a second workflow publishes it as `latest/edge/pr-$pr_id`
5. If you want to publish an update, simply add a commit to the PR, e.g. by touching a file or by changing the version in `snapcraft.yaml`

The advantages:
- The author themselves can request a build/publish if they have been vetted ('safe to publish')
- The build process for the PR will never have access to the snapcraft token
- Builds requiring changes to snapcraft.yaml, e.g. new dependencies, can be implemented via this system, too

**Comment by luzpaz** [comment]
> 2. You or the author create a PR on the FreeCAD-snap with the `source-branch` or `source-commit` pointing to their repo/branch

@ppd can you elaborate on what a demonstration commit would looks like?

**Comment by ppd** [comment]
Do you have a concrete branch in mind?

**Comment by luzpaz** [comment]
Branch: https://github.com/WandererFan/FreeCAD/tree/hlrThreadrc1  
Thread: https://forum.freecadweb.org/viewtopic.php?p=611590#p611590

CC @wandererfan

**Pull request closed without merging**
