### PR TITLE
Ship ThirdPartyLibraries.html and LICENSE.html

### PR DESCRIPTION
**Pull request by adrianinsaval**
Potential fix for #135 @luzpaz can you test this change somehow?

### CODE REVIEW

**Comment by luzpaz** [comment]
@adrianinsaval merge it and i'll trigger a daily build and test. That's the only way i can test.

**Comment by adrianinsaval** [comment]
I don't have merge rights in this repo

**Comment by luzpaz** [comment]
Triggered Daily build. Waiting for it to complete and will test.

**Comment by luzpaz** [comment]
Looks like the issue is still not fixed. 
```
connect failed: No such file or directory
QTextBrowser: No document for file:////snap/freecad/1243/usr/share/doc/FreeCAD//ThirdPartyLibraries.html
```
```
OS: Ubuntu Core 22 (KDE/plasma/xcb)
Architecture: x86_64
Version: 1.1.0dev.39748 (Git) Snap 1243
Build type: Release
Branch: main
Hash: e977eb49e37ef836f695809263fa1f56a17cc657
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: FreeCAD Dark.qss/FreeCAD Dark/Fusion
```

Separate issue:  
I wonder if the `connect failed: No such file or directory` is related to spacenavd and the spacemouse  ?

**Comment by furgo16** [comment]
> I wonder if the connect failed: No such file or directory is related to spacenavd and the spacemouse ?

Doing a cursory search on that error message + "freecad" seems to indicate that that is the case.

**Pull request merged**
