### PR TITLE
branch: Multithread Testing

### PR DESCRIPTION
**Pull request by ppd**
See https://forum.freecadweb.org/viewtopic.php?p=611590#p611590

@luzpaz 

1. Just create a commit like this in a branch and then create a PR from  it.
2. Assign the label "safe to publish" to the PR

### CODE REVIEW

**Comment by ppd** [comment]
@luzpaz Because I assigned the label, the Build PR workflow will run now. If you want to trigger another build, simply push another commit to this branch, e.g. by creating a file `build-trigger` and putting an integer into it.

**Comment by ppd** [comment]
As you can see, this combination of workflows allows to pick any branch in any FreeCAD repo while _also_ giving you the choice to edit every file relating to the snap itself. For example, you could add dependencies and so forth. 

You can teach people to create a PR themselves so that  they can control when to

**Comment by ppd** [comment]
@luzpaz See the comment by the github-actions bot for the channel the snap gets published in; it corresponds to the PR's number. 

Does this all make sense to you?

**Comment by ppd** [comment]
@wandererfan You can also ping here if you have new commits to build.

**Comment by WandererFan** [comment]
could we build another snap from this PR, please? 

also, are there instructions on how users can access this for testing somewhere?  I thought I had made a note to myself, but I can't find it now.

**Comment by ppd** [comment]
> could we build another snap from this PR, please?

Build will be ready in ~2 hours.

> also, are there instructions on how users can access this for testing somewhere? 

```shell
# new install
sudo snap install --channel=edge/pr-44 freecad
# change snap channel
sudo snap refresh --channel=edge/pr-44 freecad
```

**Comment by luzpaz** [comment]
@WandererFan I've re-triggered building the snap for the multithread PR (see [de1931c](https://github.com/FreeCAD/FreeCAD-snap/pull/44/commits/de1931c8b53c004d7dc354623e6efa15f3e10afe)). Do you want permissions to be able to do this as well ?

**Comment by WandererFan** [comment]
"Do you want permissions to be able to do this as well ?"

@luzpaz : Yes, please.

**Comment by luzpaz** [comment]
@WandererFan Done! You have write access to this repo. :partying_face: 
Also check out the docs i wrote on how to trigger builds from clones (#45)

**Comment by ppd** [comment]
@luzpaz you don't need to give people write access to this repo (in general). A PR from them is sufficient as long as you assign the safe for publishing label.

**Comment by luzpaz** [comment]
@WandererFan I've re-triggered the snap to build https://github.com/FreeCAD/FreeCAD/pull/7224/commits/72490d8a2659abbad6526ea7ea269240e1d49791

**Comment by luzpaz** [comment]
@WandererFan looks like the original PR was closed. Please advise

**Comment by WandererFan** [comment]
> @WandererFan looks like the original PR was closed. Please advise

Made a new branch with some additional cleanups.  Further testing will be in master(!). 

Thanks for all your help.

**Comment by luzpaz** [comment]
@WandererFan can you provide a link?

**Comment by luzpaz** [comment]
Closing experimental branch

**Pull request closed without merging**
