### PR TITLE
Test Build: Sketcher tangents at knots

### PR DESCRIPTION
**Pull request by AjinkyaDahale**
Replaces #59 because changed branch name.

Making a new snap since
1. This is a new stage after #56.
2. This will allow me to refresh builds without having to bother @luzpaz.

### CODE REVIEW

**Comment by luzpaz** [comment]
@AjinkyaDahale  Maybe the reason for the lack of 'Installation instructions' that are usually displayed when is build is done is one needs to add the 'safe to publish' tag before the build ends? Just a thought

**Comment by AjinkyaDahale** [comment]
@luzpaz possibly. Let me retrigger.

**Comment by ppd** [comment]
Oh no, sorry. That's an issue with the publish PR workflow. You did everything right. I'll fix this.

**Comment by AjinkyaDahale** [comment]
@ppd I got an email saying some "Publish PR #85" failed. Something you're trying?

**Comment by ppd** [comment]
@AjinkyaDahale Yes, indeed. Should be working soon.

**Comment by AjinkyaDahale** [comment]
Closing this PR in favor or $65, which contains all B-spline features currently in PR or in development. Anybody who wants to try only individual PRs in master (for whatever reason) can just build them directly.

**Pull request closed without merging**
